config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/accueils/dashboard', as: 'rails_admin'
  devise_for :structures, controllers: {
    registrations: 'structures/registrations', # Contrôleur de registration personnalisé pour Structure
    sessions: 'structures/sessions',   
    confirmations: 'structures/confirmations', 
    passwords: 'structures/passwords',             # Contrôleur de sessions personnalisé pour Structure
    # ... d'autres contrôleurs si nécessaire
  }



  devise_for :users, controllers: {
    registrations: 'users/registrations', # Contrôleur de registration personnalisé pour User
    sessions: 'users/sessions',
    confirmations: 'users/confirmations', 
    passwords: 'users/passwords',             # Contrôleur de sessions personnalisé pour User
    # ... d'autres contrôleurs si nécessaire
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest', as: :guest_sign_in
    post 'users/admin_guest_sign_in', to: 'users/sessions#new_admin_guest', as: :admin_guest_sign_in
  end


  devise_scope :structure do
    post 'structures/structure_sign_in', to: 'structures/sessions#new_guest', as: :structure_sign_in
  end
  
  root 'accueils#index'
  resources :conversations, only: [:index, :show]
  

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :structures do
      get 'annonces', on: :member  # Cette route agira sur la collection d'articles
      get 'avis_offres', on: :member
      get 'subscribers', on: :member
      post 'create_profile', on: :member
      resources :abonnements , only: [:create, :destroy]
  end

  resources :users do
    get 'a_la_une_for_user', on: :member
    get 'structures', on: :member
    member do
      patch 'update_admin'
    end
  end

  resources :annonces do
    resources :annonce_comments, only: [:create, :edit, :update, :destroy]
  end

  resources :avis_offres do
    resources :avis_offre_comments, only: [:create, :edit, :update, :destroy]
  end  
  resources :profile_structures
  resources :profile_users

  resources :activites
  resources :accueils do
    get 'dashboard'
  end  
  
  get 'accueils/a_la_une_for_others', to: 'accueils#a_la_une_for_others', as: :a_la_une_for_others

  get 'accueils/dashboard', to: 'accueils#dashboard', as: :dashboard

  #resources :utilisateurs, only: [:new, :create, :edit, :update, :destroy]
  #resources :structures, only: [:new, :create, :edit, :update, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :annonce_comments, dependent: :destroy
  has_many :avis_offre_comments, dependent: :destroy
  has_one :profile_user, dependent: :destroy
  has_and_belongs_to_many :activites
  has_many :abonnements, dependent: :destroy
  has_many :structures, through: :abonnements 
  enum role: { utilisateur: 0, structure: 1 }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable


  scope :subscribed, ->(user_id, structure_id) do
    joins(:abonnements)
      .where(id: user_id, abonnements: { structure_id: structure_id })
      .exists?
  end

  def est_abonner(structure_id)
    structures = current_user.structures
    structure = Structure.find(structure_id)
  
    for value in structures do
      if value.eql?(structure)
        return true
      end
    end
  
    false
  end
  
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

    def create
        super do |resource|
            resource.activite_ids = params[:user][:activite_ids]
            resource.save
        end
    end

    
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
    def destroy
        super
    end


    def new_guest
        user = User.find_or_create_by(email: 'guest@example.com') do |user|
        user.password = SecureRandom.hex(10)
        user.password_confirmation = user.password
        user.name = 'Guest User'
        user.admin = false      
        activites_ids = [1, 2, 3] # IDs des activités préférées de l'utilisateur
        user.activites << Activite.where(id: activites_ids)
        user.skip_confirmation!
        end
        sign_in user
        redirect_to root_path, notice: "Connecté(e) en tant qu'utilisateur(trice) invité !"
    end

    def new_admin_guest
        user = User.find_or_create_by(email: 'admin_guest@example.com') do |user|
        user.password = SecureRandom.hex(10)
        user.password_confirmation = user.password
        user.name = 'Guest Admin'
        user.admin = true
        activites_ids = [1, 2, 3] # IDs des activités préférées de l'utilisateur
        user.activites << Activite.where(id: activites_ids)
        user.skip_confirmation!
        end
        sign_in user
        redirect_to root_path, notice: "Connecté(e) en tant qu'administrateur(trice) invitée!"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: %i[ structures a_la_une_for_user destroy]

    def structures
      @structures = @user.structures.page(params[:page])
    end  

    def a_la_une_for_user
      @annonces = Annonce.latest_by_structure_with_matching_activites(@user).page(params[:page])
      @avis_offres = AvisOffre.latest_by_structure_with_matching_activites(@user).page(params[:page])
    end  

    # GET /structures or /structures.json 
    def index
      @q = User.ransack(params[:q])
      @users = @q.result(distinct: true).page(params[:page])
    end

    def show
      # Ajoutez le code nécessaire pour gérer l'action show ici
      # Par exemple, si vous souhaitez afficher les détails d'un utilisateur
      redirect_to root_path
    end

    def destroy
      @user.destroy

      respond_to do |format|
        format.html { redirect_to users_url, notice: "Annonce was successfully destroyed." }
        format.json { head :no_content }
      end
    end 

    def update_admin
      @user = User.find(params[:id])
      @user.update(admin: !@user.admin)
      redirect_to users_path, notice: 'Admin status updated successfully.'
    end
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_user
        @user = User.find(params[:id])
      end
end

app/helpers/users/confirmations_helper.rb
module Users::ConfirmationsHelper
end

app/helpers/users/passwords_helper.rb
module Users::PasswordsHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users/sessions_helper.rb
module Users::SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
 
end

app/views/users/a_la_une_for_user.html.erb
<h2>Annonce</h2>

<div class="row mt-5 mb5">
      <% @annonces.each do |annonce| %>
          <div class="col-sm-6">
            <div class="card">
              <div class="card-body">
                <div class="second_style">
                  <%= image_tag annonce.image.variant(resize_to_limit: [100, 800]) if annonce.image.attached? %> 
                </div>
                <h5 class="card-title">
                   <%= annonce.title %>
                </h5>
                <p class="card-text">
                    <%= annonce.purpose %>
                </p>
                <div class="gosomwhere">
                    <%= link_to 'Voir', annonce , class:" btn btn-info" %>
                </div>
              </div>
            </div>
          </div>
      <% end %>
</div>
<div class="pagination">
    <%= paginate @annonces%>
</div>    

<h2>Avis offres</h2>

<div class="row mt-5">
      <% @avis_offres.each do |avis_offre| %>
          <div class="col-sm-6">
            <div class="card">
              <div class="card-body">
                <div class="second_style">
                  <%= image_tag avis_offre.image.variant(resize_to_limit: [100, 800]) if avis_offre.image.attached? %> 
                </div>
                <h5 class="card-title">
                   <%= avis_offre.title %>
                </h5>
                <p class="card-text">
                    <%= avis_offre.purpose %>
                </p>
                <div class="gosomwhere">
                    <%= link_to 'Voir', avis_offre , class:" btn btn-info" %>
                </div>
              </div>
            </div>
          </div>
      <% end %>
</div>
<div class="pagination">
    <%= paginate @avis_offres%>
</div>    

app/views/users/index.html.erb
<h1>Utilisateurs</h1>
<%if !user_signed_in? %>
  <% if user_signed_in? && current_user.try(:admin?) %>
      <td><%= link_to 'Ajouter utilisateur', new_user_registration_path , class:"mb-5 button btn btn-info"%></td>
  <% end %>
<% end %>




<br>

<div class="mb-4">
  <%= search_form_for @q do |f| %>
    <div class="form-group">
      <%= f.label :name_cont, "Nom" %>
      <%= f.search_field :name_cont, class: "form-control", placeholder: "Titre" %>
  </div>

    <%= f.submit "Rechercher", class: "btn btn-primary" %>
  <% end %>
</div>




<div class="content">
        <div class="col-md-12 container  mx-auto table-responsive">
            <table class=" mt-5">
                <thead>
                    <tr>
                        <th class="gauche" scope="col">Nom</th>
                        <th scope="col" class="milieu">Email</th>
                        <th scope="col">Admin</th>
                        
                        <!-- <th scope="col">Statut</th> -->
                        <th class="droite" scope="col">Actions</th>
                    </tr>


                </thead>

                <tbody>
                  <% @users.each do |user| %>
                    <tr >
                        <td><%= user.name %></td>
                        <td> <%= user.email %></td>
                        <td>
                           <% if user.admin.present? %>
                            <%= user.admin %>
                           <% else %>
                           false
                           <%end%> 
                        </td>
                        <td>
                          <span>
                            <%= link_to update_admin_user_path(user), method: :patch, remote: true  do%>
                              <i class="fas fa-edit edit"></i>
                            <% end %>
                          </span>

                          <span>
                            <%= link_to user_path(user) , data: { confirm: "本当に削除しますか?"}, method: :delete, remote: true  do%>
                              <i class="fas fa-trash delete "></i>
                            <% end %>
                          </span>     

                          <span>
                            <%= link_to profile_user_path(user)  do%>
                              <i class="fas fa-eye "></i>
                            <% end %>
                          </span>                   
                        </td>
                        <!-- <td>thththththththththththththththththththththt</td> -->
            

                    </tr>
                  <% end %>
                </tbody>
            </table>
            <div class="pag" style="font-size: 18px; color: black;">
                
            </div>
        </div>       
</div>
<div class="pagination">
    <%= paginate @users%>
</div>    