config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/accueils/dashboard', as: 'rails_admin'
  devise_for :structures, controllers: {
    registrations: 'structures/registrations', # Contrôleur de registration personnalisé pour Structure
    sessions: 'structures/sessions',   
    confirmations: 'structures/confirmations', 
    passwords: 'structures/passwords',             # Contrôleur de sessions personnalisé pour Structure
    # ... d'autres contrôleurs si nécessaire
  }



  devise_for :users, controllers: {
    registrations: 'users/registrations', # Contrôleur de registration personnalisé pour User
    sessions: 'users/sessions',
    confirmations: 'users/confirmations', 
    passwords: 'users/passwords',             # Contrôleur de sessions personnalisé pour User
    # ... d'autres contrôleurs si nécessaire
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest', as: :guest_sign_in
    post 'users/admin_guest_sign_in', to: 'users/sessions#new_admin_guest', as: :admin_guest_sign_in
  end


  devise_scope :structure do
    post 'structures/structure_sign_in', to: 'structures/sessions#new_guest', as: :structure_sign_in
  end
  
  root 'accueils#index'
  resources :conversations, only: [:index, :show]
  

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :structures do
      get 'annonces', on: :member  # Cette route agira sur la collection d'articles
      get 'avis_offres', on: :member
      get 'subscribers', on: :member
      post 'create_profile', on: :member
      resources :abonnements , only: [:create, :destroy]
  end

  resources :users do
    get 'a_la_une_for_user', on: :member
    get 'structures', on: :member
    member do
      patch 'update_admin'
    end
  end

  resources :annonces do
    resources :annonce_comments, only: [:create, :edit, :update, :destroy]
  end

  resources :avis_offres do
    resources :avis_offre_comments, only: [:create, :edit, :update, :destroy]
  end  
  resources :profile_structures
  resources :profile_users

  resources :activites
  resources :accueils do
    get 'dashboard'
  end  
  
  get 'accueils/a_la_une_for_others', to: 'accueils#a_la_une_for_others', as: :a_la_une_for_others

  get 'accueils/dashboard', to: 'accueils#dashboard', as: :dashboard

  #resources :utilisateurs, only: [:new, :create, :edit, :update, :destroy]
  #resources :structures, only: [:new, :create, :edit, :update, :destroy]
end

app/models/activite.rb
class Activite < ApplicationRecord
    validates :name, presence: true
    validates :name, length: {maximum: 250}

    has_and_belongs_to_many :structures
    has_and_belongs_to_many :users
end

app/controllers/activites_controller.rb
class ActivitesController < ApplicationController
    before_action :set_activite, only: %i[ show edit update destroy ]

    
      # GET /blogs or /blogs.json
      def index
        @activites = Activite.all
      end
    
  
      # GET /blogs/new
      def new
        @activite = Activite.new
        @activites = Activite.all
      end
    
      # GET /blogs/1/edit
      def edit
      end
    
      # POST /blogs or /blogs.json
      def create
        @activite = Activite.new(activite_params)
    
        respond_to do |format|
          if @activite.save
            format.html { redirect_to activite_url(@activite), notice: "Avis offre was successfully created." }
            format.json { render :show, status: :created, location: @activite }
          else
            format.html { render :new, status: :unprocessable_entity }
            format.json { render json: @activite.errors, status: :unprocessable_entity }
          end
        end
      end
    
      # PATCH/PUT /blogs/1 or /blogs/1.json
      def update
        respond_to do |format|
          if @activite.update(activite_params)
            format.html { redirect_to activite_url(@activite), notice: "Avis offre was successfully updated." }
            format.json { render :show, status: :ok, location: @activite }
          else
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @activite.errors, status: :unprocessable_entity }
          end
        end
      end
    
      # DELETE /blogs/1 or /blogs/1.json
      def destroy
        @activite.destroy
    
        respond_to do |format|
          format.html { redirect_to activites_url, notice: "Avis offre was successfully destroyed." }
          format.json { head :no_content }
        end
      end
    
      private
        # Use callbacks to share common setup or constraints between actions.
        def set_activite
          @activite = Activite.find(params[:id])
        end
    
        # Only allow a list of trusted parameters through.
        def activite_params
          params.require(:activite).permit(:name)
        end
end

app/helpers/activites_helper.rb
module ActivitesHelper
end

app/views/activites/_form.html.erb
<%= form_with(model: activite, local: true) do |form| %>
  <% if activite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(activite.errors.count, "error") %> prohibited this activite from being saved:</h2>

      <ul>
        <% activite.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-floating mt-4">
    <%= form.label :nom %>
    <%= form.text_field :name , placeholder: "Entrer le nom...", class: "form-control", id: "inputNom"%>
  </div>


  <div class="form-floating mt-4 submit">
    <%= form.submit "Créer", class: "btn btn-success"%>
  </div>
<% end %>

app/views/activites/edit.html.erb
<h1>Edit Activite</h1>

<%= render 'form', activite: @activite %>


<%= link_to 'Back', activites_path , class:"back btn btn-info"%>

app/views/activites/index.html.erb
<h1>
Liste des activités
</h1>
<div class="row mt-5 mb5">
      <% @activites.each do |activite| %>
          <div class="col-sm-6">
           
                <h5 class="card-title">
                   <%= activite.name %>
                   <%= link_to 'Edit', edit_activite_path(activite) , class:"btn btn-warning"%> 
                   <%= link_to 'Destroy', activite, method: :delete, data: { confirm: 'Are you sure?' } , class:"btn btn-danger" %>
                </h5>
          </div>
      <% end %>
</div>
<%= link_to 'Back', :back , class:"back btn btn-info"%>

app/views/activites/new.html.erb
<h1>Nouvelle Activite</h1>

<%= render 'form', activite: @activite %>



<%= link_to 'Back', activites_path , class:"back btn btn-info"%>

<%= link_to 'Liste ds activités', activites_path , class:" btn btn-light"%>

app/views/activites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @activite.name %>
</p>



<%= link_to 'Edit', edit_activite_path(@activite) %> |
<%= link_to 'Destroy', @activite, method: :delete, data: { confirm: 'Are you sure?' } %>|
<%= link_to 'Back', activites_path %>