config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/accueils/dashboard', as: 'rails_admin'
  devise_for :structures, controllers: {
    registrations: 'structures/registrations', # Contrôleur de registration personnalisé pour Structure
    sessions: 'structures/sessions',   
    confirmations: 'structures/confirmations', 
    passwords: 'structures/passwords',             # Contrôleur de sessions personnalisé pour Structure
    # ... d'autres contrôleurs si nécessaire
  }



  devise_for :users, controllers: {
    registrations: 'users/registrations', # Contrôleur de registration personnalisé pour User
    sessions: 'users/sessions',
    confirmations: 'users/confirmations', 
    passwords: 'users/passwords',             # Contrôleur de sessions personnalisé pour User
    # ... d'autres contrôleurs si nécessaire
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest', as: :guest_sign_in
    post 'users/admin_guest_sign_in', to: 'users/sessions#new_admin_guest', as: :admin_guest_sign_in
  end


  devise_scope :structure do
    post 'structures/structure_sign_in', to: 'structures/sessions#new_guest', as: :structure_sign_in
  end
  
  root 'accueils#index'
  resources :conversations, only: [:index, :show]
  

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :structures do
      get 'annonces', on: :member  # Cette route agira sur la collection d'articles
      get 'avis_offres', on: :member
      get 'subscribers', on: :member
      post 'create_profile', on: :member
      resources :abonnements , only: [:create, :destroy]
  end

  resources :users do
    get 'a_la_une_for_user', on: :member
    get 'structures', on: :member
    member do
      patch 'update_admin'
    end
  end

  resources :annonces do
    resources :annonce_comments, only: [:create, :edit, :update, :destroy]
  end

  resources :avis_offres do
    resources :avis_offre_comments, only: [:create, :edit, :update, :destroy]
  end  
  resources :profile_structures
  resources :profile_users

  resources :activites
  resources :accueils do
    get 'dashboard'
  end  
  
  get 'accueils/a_la_une_for_others', to: 'accueils#a_la_une_for_others', as: :a_la_une_for_others

  get 'accueils/dashboard', to: 'accueils#dashboard', as: :dashboard

  #resources :utilisateurs, only: [:new, :create, :edit, :update, :destroy]
  #resources :structures, only: [:new, :create, :edit, :update, :destroy]
end

app/models/profile_user.rb
class ProfileUser < ApplicationRecord
    validates :nom, :prenom,:genre,:situation,:numero, presence: true
    validates :nom, :prenom,:genre,:situation,:numero, length: {maximum: 250}

    belongs_to :user
        has_one_attached :image
end

app/controllers/profile_users_controller.rb
class ProfileUsersController < ApplicationController
    before_action :set_profile, only: %i[ show  ]

    def new
      @profile_user = ProfileUser.new
    end  

    def show
        @profile_user = @user.profile_user
    end

    def edit
        @profile_user = current_user.profile_user
    end  

    def update
      @profile_user = current_user.profile_user
      respond_to do |format|
        if @profile_user.update(profile_params)
          format.html { redirect_to accueils_path(), notice: "Profile user was successfully updated." }
          #format.json { render :show, status: :created, location: @profile_user }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @profile_user.errors, status: :unprocessable_entity }
        end
      end
    end


    def create
      @profile_user = ProfileUser.new(profile_params)
  
      respond_to do |format|
        if @profile_user.save
          format.html { redirect_to accueils_path, notice: "Profile user was successfully created." }
          format.json { render :show, status: :created, location: @profile_user }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @profile_user.errors, status: :unprocessable_entity }
        end
      end
    end


    def destroy
      @profile_user = ProfileUser.find(params[:id]) 
      @profile_user.destroy

      respond_to do |format|
        format.html { redirect_to accueils_url, notice: "Annonce was successfully destroyed." }
        format.json { head :no_content }
      end
    end 

    private
      def set_profile
        if user_signed_in?
            @user = User.find(params[:id])
            @profile_user = @user.profile_user
        else
          @user = User.find(params[:id]) 
          @profile_user = @user.profile_user
        end
      end  

      def profile_params
        params.require(:profile_user).permit(:nom, :prenom, :genre, :situation, :numero, :user_id, :image)
      end
end

app/helpers/profile_users_helper.rb
module ProfileUsersHelper
    def profile_empty?(user)
        if current_user.admin?
            current_user.profile_user.nil?
        else   
            user.profile_user.nil?
        end    
    end
end

app/views/profile_users/_form.html.erb
<%= form_with(model: profile_user, local: true) do |form| %>
  <% if profile_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile_user.errors.count, "error") %> prohibited this profile user from being saved:</h2>

      <ul>
        <% profile_user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-floating mt-4 ">
    <%= form.label :nom %>
    <%= form.text_field :nom , class: "form-control", id: "inputNom"%>
  </div>

  <div class="form-floating mt-4 ">
    <%= form.label :prenom %>
    <%= form.text_field :prenom , class: "form-control", id: "inputPrenom"%>
  </div>

  <div class="form-floating mt-4 ">
    <%= form.label :genre %>
    <%= form.text_field :genre , class: "form-control", id: "inputGenre"%>
  </div>

  <div class="form-floating mt-4 ">
    <%= form.label :situation %>
    <%= form.text_field :situation , class: "form-control", id: "inputSituation"%>
  </div>

  <div class="form-floating mt-4 ">
    <%= form.label :numero %>
    <%= form.text_field :numero , class: "form-control", id: "inputNumero"%>
  </div>

  <div class="form-floating mt-4 ">
    <%= form.label :image %>
    <%= form.file_field :image , class: "form-control", id: "inputImage"%>
  </div>


  <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="form-floating mt-4 mb-4 submit ">
    <%= form.submit class: "btn btn-success", style:"width:25%;"%>
  </div>
<% end %>

app/views/profile_users/edit.html.erb
<h1>Edit Profile utilisateur</h1>

<%= render 'form', profile_user: @profile_user %>


<%= link_to 'Back', :back , class: "back btn btn-info"%>
<%= link_to 'Voir', profile_user_path(current_user) , class: " btn btn-succcess"%>

app/views/profile_users/new.html.erb
<h1>Nouveau Profile user</h1>

<%= render 'form', profile_user: @profile_user %>

<%= link_to 'Back', profile_users_path , class: "back btn btn-info"%>